- ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/product/v1/product/clientlib/js/gallery.js
Fixes a bug that caused the main product image to not update when selecting a product variant.
Fixes #8.
> #8 - Main image doesn't change when selecting another color

- ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/product/v1/product/clientlib/js/gallery.js
- ui.apps/src/main/content/jcr_root/apps/venia/components/structure/header/v1/header/clientlibs/js/searchbar.js
Some JavaScript code in the product and search components used a syntax that's not supported by Safari and Firefox yet, which broke the components.
> CIF-839 - Fix JS errors of product and search components in Safari/Firefox

- dispatcher/README.md
Update README with the information regarding the configuration of the dispatcher in front of the authoring instance.
CIF-825
Documentation update
N/A
> CIF-825 - AEM Dispatcher configuration for Magento integration

- ui.content/src/main/content/jcr_root/content/venia/language-masters/en/.content.xml
- ui.content/src/main/content/jcr_root/content/venia/us/en/.content.xml
- ui.content/src/main/content/jcr_root/content/venia/us/en/search/.content.xml
Fixes broken search page for /content/venia/us/en site and search page referenece.
CIF-845
Locally & manually
> CIF-845 fixes broken search page

- all/pom.xml
- ui.apps/src/main/content/jcr_root/apps/venia/components/structure/header/v1/header/clientlibs/js/searchbar.js
When clicking on the search icon, the search input field is now automatically focused, so a user can directly start typing.
Tested in Chrome, Safari and Firefox.
> CIF-859 - Focus searchbar on click on search icon

- ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/product/v1/product/quantity.html
Fix styling of quantity input box on product detail page to look like in Venia.
> CIF-856 - Fix styling for quantity input on product detail page

- dispatcher/Dockerfile
- dispatcher/conf/dispatcher.any
- set right ownership on 'htdocs'
- minor fix to allow .svg images
> CIF-863 - Dispatcher does not have write permissions in cache folder

- README.md
Add video link.
n/a
Add video link documenting the setup process.
> @trivial Update readme.md

- ui.apps/src/main/content/jcr_root/apps/venia/components/structure/catalogpage/v1/catalogpage/.content.xml
- ui.apps/src/main/content/jcr_root/apps/venia/components/structure/footer/v1/footer/.content.xml
- ui.apps/src/main/content/jcr_root/apps/venia/components/structure/header/v1/header/.content.xml
- ui.apps/src/main/content/jcr_root/apps/venia/components/structure/navigation/v1/navigation/.content.xml
Hide structure component in Sites editor.
> CIF-844 - Structure components are visible in the page component list

- ui.apps/src/main/content/jcr_root/apps/venia/components/structure/header/v1/header/clientlibs/css.txt
- ui.apps/src/main/content/jcr_root/apps/venia/components/structure/header/v1/header/clientlibs/css/header-aem.css
- ui.apps/src/main/content/jcr_root/apps/venia/components/structure/header/v1/header/clientlibs/css/header-component.css
Fix the Venia header and make it sticky.
CIF-808
> CIF-808 - fix sticky Venia header

- ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/minicart/v1/minicart/clientlib/.content.xml
- ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/product/v1/product/clientlib/.content.xml
- ui.apps/src/main/content/jcr_root/apps/venia/components/content/heroimage/v1/heroimage/clientlibs/.content.xml
- added missing "allowProxy" property
> CIF-887 - Some clientlibs are not available on publish instance

- ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/common/js/CommerceGraphqlApi.js
Bug fix:
- there is no thumbnail for the shopping cart item if there's only one item in the cart.
CIF-747
N/A
N/A
> CIF-747 - Shopping cart popup

- ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/productlist/v1/productlist/README.md
All CIF core components should get their dedicated readme to describe the functionality, configuration & customization options and how to use be project developers. The goal is to align with AEM sites core components to give developers a similar experience.
This is the first readme.md which, once merged, should be the reference for the other components. In the future, all components will require a readme like this one.
> CIF--892 - add product list readme

- all/pom.xml
Minor fix for parent pom.xml path for all package
CIF-912
> CIF-912 - fix parent pom.xml path for all package

- README.md
- all/pom.xml
- parent/pom.xml
- pom.xml
- ui.apps/src/main/content/META-INF/vault/definition/.content.xml
Re-add all content package which was removed during the cleanup.
CIF-888
Re-add all content package to have one single dependency for customer projects.
- [] New feature (non-breaking change which adds functionality)
> CIF-888 - re-add all content package

- .circleci/config.yml
setup release process - fix circleci config
CIF-883
> CIF-883 - setup release process - fix circleci config

- README.md
Minor clean up on readme.md
CIF-883
Highlight all the components we currently have.
> CIF-883 - post release cleanup

- README.md
- VERSIONS.md
- parent/pom.xml
Update readme.md & version.md to show the correct versions, add badges and prepare automatic release propagation on maven central for next release.
CIF-883
Improve readme.md and simplify the next release.
> CIF-883 Post release tasks

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/README.md
* add product teaser readme
* fix typos in product list readme
CIF-893
Each CIF component should have a basic readme.
> CIF-893 - add product teaser readme

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
- ui.apps/karma.conf.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js.txt
- ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/PriceFormatter.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/product.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/clientlibs/dist/js/productlist.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/clientlibs/js.txt
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/item.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/productlist.html
- ui.apps/src/test/clientlibs/common/priceFormatterTest.js
- ui.apps/src/test/components/commerce/product/productTest.js
- ui.apps/src/test/components/commerce/productlist/productListTest.js
The price listed on the bottom of the image (attached) needs to be client-side rendered. This is because price could be a personalized product attribute and showing this as client-side rendered in the reference product detail component will provide developers with an example to showcase how server-side rendered content can be enhanced with client-side content.
~This PR is on top of https://github.com/adobe/aem-core-cif-components/pull/62, since it uses the same library. Please review the other PR first.~
> CIF-804 - AEM core component - Product List with Price (CSR)

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java
- ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/_cq_design_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/product.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/_cq_design_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/clientlibs/dist/js/productlist.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/productlist.html
- ui.apps/src/test/components/commerce/product/productTest.js
- ui.apps/src/test/components/commerce/productlist/productListTest.js
* Added options in design dialog of product and productlist components to disable client-side price fetching.
* Minimize GraphQL queries for smaller footprint of GraphQL requests
* Improved error handling in GraphQL client
* Also contains feedback from https://github.com/adobe/aem-core-cif-components/pull/64 and https://github.com/adobe/aem-core-cif-components/pull/62.
> CIF-743/CIF-804 - Add option to enable and disable client-side price fetching

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/README.md
* Added readme for product component
* Added design option for loading client-side prices in productlist readme
> CIF-891 - Add readme for product component

- ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/minicart/v1/minicart/clientlib/js/MiniCart.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToCart.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/header/v1/header/clientlibs/js/cartTrigger.js
The minicart and related components printed a lot of debug messages in the JavaScript console. These log statement where removed now.
> CIF-921 - Remove console log statements of cart

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCateogoryListImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCateogoryListImplTest.java
Improved test cases with better coverage.
CIF-879 
This pull request contains changes in the test case and 
Run test case with build and verify , Verify code coverage.
> CIF -879 Improved test cases with better coverage.

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/README.md
Add navigation component readme.md
CIF-897
All CIF Core Components should have a basic readme.
>  CIF-897 - add navigation component readme.md

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCateogoryListImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCateogoryListImplTest.java
- bundles/core/src/test/resources/graphql/magento-graphql-singlecategory-result.json
- dispatcher/conf/dispatcher.any
- dispatcher/conf/magento-proxy.conf
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html
This PR improves the way the category image is loaded. Does not require additional AEM Dispatcher config any more and use the same URL construction (Magento media base url + folder + image) like other components we have.
CIF-879  
Improve image URLs and align with other components.
> CIF-879 - improve category image loading

- README.md
- VERSIONS.md
CIF-844 update version in readme.md & version.md after release
> CIF-844 update version after release

- bundles/core/pom.xml
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/GraphqlClientDataSourceServlet.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/GraphqlClientDataSourceServletTest.java
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/catalogpage/v1/catalogpage/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml
* Created datasource servlet to retrieve all available GraphQL clients
* Added select field to CIF page properties to select GraphQL client for the subtree. An empty option `Inherit` is provided that removes the property from the node.
* Added textfield to CIF page properties to specify Magento store view.
* Updated dialog of `catalogpage` component so that the merge of the dialogs works properly.
* Added unit tests for datasource servlet.
> CIF-756 - Manually configuration of used GraphQL client/catalog

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
Remove unused logger from product teaser impl.
> @trivial - remove unused logger

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/css.txt
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/clientlib/css/teaser.css
> CIF-876 - AEM core component - Teaser

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
- bundles/core/src/test/resources/context/jcr-content.json
- fixed unit test to properly inject the sling model
- added more branching coverage
- refactored impl code to remove useless 'this' keyword
> CIF-1024 - Fix unit tests for productlist component

- ui.apps/package-lock.json
- ui.apps/package.json
Fix GH security warnings on NPM dependencies.
n/a
> @trivial - fix GH security warnings

- dispatcher/conf/magento-proxy.conf
> CIF-1031 - Clean up magento-proxy.conf

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_design_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_design_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/_cq_design_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_design_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/_cq_design_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v1/button/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v1/button/_cq_design_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/_cq_design_dialog/.content.xml
* Added style system support for the following components:
* Featured Category List
* Product Detail
* Product Carousel
* Product List
* Product Teaser
* Product Search Results
* Button
* Teaser
Example styles for the product list component are added with https://github.com/adobe/aem-cif-project-archetype/pull/47.
Please also see:
* [Understanding how to code for the Style System](https://docs.adobe.com/content/help/en/experience-manager-learn/sites/developing/style-system-technical-video-understand.html)
* [Style System Documentation](https://helpx.adobe.com/experience-manager/6-5/sites/authoring/using/style-system.html)
Closes https://github.com/adobe/aem-core-cif-components/pull/41.
> CIF-1033 - Enable Style System for CIF Core Components

- bundles/core/pom.xml
Prepare for Magento 2.3.3 compatibility
CIF-1057
> CIF-1057 - prepare for Magento 2.3.3 compatibility

- ui.apps/pom.xml
Update dependency to CIF connector 0.6.0
> releng - Update dependency to CIF connector 0.6.0

- dispatcher/Dockerfile
Upgrade dispatcher version to 4.3.3, since 4.3.2 is no longer available.
> trivial - Upgrade dispatcher version to 4.3.3

- README.md
- ui.apps/src/main/javascript/minicart/src/components/CreateAccount/__test__/createAccount.test.js
Documentation update
N/A
N/A
N/A
> @trivial Update README with the Sign In and Create Account components

- ui.apps/src/main/javascript/minicart/src/context/UserContext.js
Reverts adobe/aem-core-cif-components#142
> Revert "CIF-1119 - Submit button on Create Account page is greyed out"

- .circleci/codecov.yml
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
- bundles/core/src/test/resources/context/jcr-content.json
- bundles/core/src/test/resources/graphql/magento-graphql-search-result.json
- replaced filter search with full-text search
- refactored unit tests to fully test the resource adaptation to the model
The search component has not been doing a full-text search, it only searched product names.
Adapted unit tests and manually tested with Magento instance.
> CIF-1121 - The search component should do a full-text search

- ui.apps/src/main/javascript/minicart/src/components/CreateAccount/__test__/createAccount.test.js
- ui.apps/src/main/javascript/minicart/src/context/UserContext.js
* User is now logged in not after retrieving a token, but only after their data was fetched from Magento. Before that change some unit tests ran into race conditions, where they would check for the logged in state by validating the user name.
* Enabled flaky unit test again.
> CIF-1109 - Fix flaky CreateAccount test

- ui.apps/pom.xml
Update dependency to CIF connector 0.7.0
> releng - Update dependency to CIF connector 0.7.0

- .github/release-drafter.yml
Add release-drafter config (see https://github.com/release-drafter/release-drafter/blob/master/README.md) to simplify the next release notes generation
Simplify the next release notes generation process.
> @trivial - add release-drafter config

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/CategoriesRetriever.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/FeaturedCategoryList.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/CategoriesRetrieverTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCateogoryListImplTest.java
- bundles/core/src/test/resources/graphql/magento-graphql-category-alias-result.json
* Instead of sending one query per category, a combined query for all categories is executed using the GraphQL alias feature.
* This is hidden behind the `AbstractCategoriesRetriever`. So if a more optimised GraphQL query is available, we can change it without touching the components.
* Unit tests
* Manual testing
> CIF-1157 - Optimize query of FeaturedCategoryList component

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/js/product-carousel.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
* Added additional CSS screen size breakpoints to make carousel component more responsive.
* Fixed positioning of the product price.
* Added handler to re-calculate state of component after the window size was changed. Otherwise the component was basically broken after a user changed the window size.
Also see https://github.com/adobe/aem-cif-project-archetype/pull/62.
* Manual testing with Chrome and Firefox.
> CIF-1164 - Improve responsiveness of product carousel component

- README.md
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsRetriever.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelationTypesDataSourceServlet.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/ProductCarousel.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelationTypesDataSourceServletTest.java
- bundles/core/src/test/resources/context/jcr-content.json
- bundles/core/src/test/resources/graphql/magento-graphql-crosssellproducts-result.json
- bundles/core/src/test/resources/graphql/magento-graphql-relatedproducts-result.json
- bundles/core/src/test/resources/graphql/magento-graphql-upsellproducts-result.json
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_dialog/.content.xml
- created new component based on product carousel
- added unit tests
- adapted carousel component and sling model to support the new component
Added unit tests, and manually tested in AEM.
> CIF-1153 - Generic related product component

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
Trivial fix to not render HTML comments.
CIF-1225
Clean HTML markup rendered
- [] I have added tests to cover my changes and the overall coverage did not decrease.
> CIF-1225 - minor fix to not render HTML comments

- bundles/core/pom.xml
- parent/pom.xml
- ui.apps/pom.xml
Update dependencies before release.
> @releng - Update dependencies before release

- README.md
- VERSIONS.md
@releng - update versions after release
> @releng - update versions after release

- README.md
> @trivial - fix component link

- README.md
Trivial - add Magento version hint to readme.md
> @trivial - add version hint to readme

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/ProductCarousel.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/searchresults/SearchResults.java
- removed all "default" methods in sling model interfaces
> CIF-1188 - Use default implementations in Sling models consistently

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/paginationbar.html
* adjusted pagination bar for larger product sets
Pagination bar should be usable with large product sets.
Related PR: https://github.com/adobe/aem-cif-project-archetype/pull/83
CIF-1224
> CIF-1224 - Pagination in productlist component cannot handle large product sets

- parent/pom.xml
Update CIF Connector dependency before release
> @trivial - update CIF Connector dependency

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplEmptyTest.java
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/js/product-carousel.js
* fix Sling exception on page when GraphQL client not found
* fix JS exception in browser console when the component is configured but no product data is available to display
CIF-1301
Manually.
> CIF-1301 - Product carousel displays exception if GraphQL client not found

- README.md
- VERSIONS.md
Update readme with new versions
> @releng - update readme

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/minicart/v1/minicart/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchbar/v1/searchbar/.content.xml
Add icons for all authorizable CIF components, see screenshot.
CIF-1223
> CIF-1223 - add cq:icon for all authorable CIF components

- react-components/__mocks__/i18nForTests.js
- react-components/package-lock.json
- react-components/package.json
- react-components/src/components/CartTrigger/__test__/__snapshots__/cartTrigger.test.js.snap
- react-components/src/components/CartTrigger/__test__/cartTrigger.test.js
- react-components/src/components/CartTrigger/cartTrigger.js
- react-components/src/components/Minicart/__test__/__snapshots__/footer.test.js.snap
- react-components/src/components/Minicart/__test__/footer.test.js
- react-components/src/components/Minicart/footer.js
- react-components/src/queries/query_cart_details.graphql
The number of items in the cart was determined using just `cart.items.length` instead of relying on the specific property from GraphQL.
The GraphQL query was updated to include the `total_quantity` property and the `Footer` component was updated to display it.
CIF-1333
Fix the display of the number of items in the cart
Functional testing and added new unit tests
> CIF-1333 - The Minicart shows an incorrect number of items

- react-components/src/components/ChangePassword/__tests_/changePassword.test.js
- react-components/src/components/Checkout/overview.js
- react-components/src/components/CreateAccount/__test__/createAccount.test.js
- react-components/src/components/CreateAccount/useCreateAccount.js
- react-components/src/components/Minicart/__test__/cartContext.test.js
- react-components/src/components/Minicart/__test__/cartHandlers.test.js
- react-components/src/components/Minicart/__test__/cartInitializer.test.js
- react-components/src/components/Minicart/cartInitializer.js
- react-components/src/components/SignIn/__test__/signIn.test.js
- react-components/src/components/SignIn/useSignin.js
- react-components/src/context/UserContext.js
Remove `console.log` statements and other debug messages
CIF-1072
"No debug messages in the console" rule
> @trivial Remove `console.log` statements and other debug messages

- README.md
- VERSIONS.md
>  @trivial - update versions

- .github/CONTRIBUTING.md
Please extend or modify directly in the branch if you want to.
> @doc - adding some guidelines for contributions and pull requests

- README.md
- VERSIONS.md
@trivial - update versions after release
n/a
Update versions after release
> @trivial - update versions after release

- dispatcher/conf/dispatcher.any
- dispatcher/conf/magento-proxy.conf
Fix dispatcher template hostnames
> @trivial - fix dispatcher template

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchResultsSetImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
Display Categories as a facet as part of faceted search
CIF-1358
Extra filters for searching
Adapted unit tests
Manual tests
> CIF-1358: Allow category filtering for searches

- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
Replaces https://github.com/adobe/aem-core-cif-components/issues/287 as the original author is not responding.
https://github.com/adobe/aem-core-cif-components/issues/286
Fixed unit test.
> Bug fix for github issue #286

- parent/pom.xml
* updated to Core WCM Components 2.9.0 which included the actual fix
CIF-1156
Manually.
> CIF-1156 - Live copy catalog does not show if node name is not language code

- README.md
- VERSIONS.md
> releng - Update release version in README

- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
- bundles/core/src/test/resources/graphql/magento-graphql-search-result-with-category.json
- bundles/core/src/test/resources/graphql/magento-graphql-search-result.json
- fix search filters when a price range has a single value
https://github.com/adobe/aem-core-cif-components/issues/317
Extended unit tests and manually tested.
> CIF-1492 - [Github] Issue #317

- .circleci/ci/build.js
- .circleci/ci/ci.js
- .circleci/ci/it-tests.js
- .circleci/config.yml
This prepares the testing infrastructure to test our components on AEM 6.5.5 and on the AEM Cloud SDK.
The next step will be to add some first basic HTTP tests to make sure that the pages of the components library can be fetched and display the expected HTTP output of each component.
The test instances currently start and all bundles properly start, although we do not yet have any integration test running.
> CIF-1497 - Setup IT infrastructure for CIF components

- react-components/webpack.config.js
Reverts adobe/aem-core-cif-components#354
> Revert "CIF-1547 - [React Components] Fix CSS reusability"

- react-components/package.json
Update react components version in order to prepare release
> @trivial: Update react-components version

- README.md
add AEM Cloud support to readme
n/a
> @trivial - add AEM Cloud support to readme

- .circleci/config.yml
- pom.xml
- fix issue with profile vs. property
Locally tested by building normally and then with `-Dskip-it`.
> CIF-1566 - Integration tests should not be released

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/description.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/quantity.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/sku.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/title.html
Extract title, description, sku into separate HTL templates for better customizability.
CIF-1539
> CIF-1539 -  Extract title, description, sku into separate templates

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/actions.html
- add label field in dialog
The change in `.content.xml` looks large because of reformatting, the main change is at the bottom with the extra `ctaText` field.
> CIF-1536 - Product teaser: Add CTA label configuration

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/head.html
* Remove Venia specific font from page component.
* Font was moved to the Venia project via .
* Manual
> CIF-1590 - Remove Venia specific font from page component

- README.md
- dispatcher/README.md
- react-components/README.md
* Added instructions for a reverse proxy to be used with Magento instead of a dispatcher.
* I also updated https://github.com/adobe/aem-core-cif-components/wiki/Configuration#cif-magento-graphql-base-configuration
* Added a note to the dispatcher documentation to not use it with AEMaaCS.
* Updated archetype link and added a link to Venia.
> CIF-1587 - Add reverse proxy to documentation

- README.md
- VERSIONS.md
> @releng - updating version numbers in docs

- .github/codecov.yml
* Fixed invalid `codecov.yml` configuration.
* Moved `codecov.yml` to `.github` folder as required by https://docs.codecov.io/docs/codecov-yaml#can-i-name-the-file-codecovyml.
> releng - Fix invalid codecov.yml configuration

- .github/codecov.yml
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplAssetsTest.java
- bundles/core/src/test/resources/graphql/magento-graphql-product-incomplete-asset-result.json
- bundles/core/src/test/resources/graphql/magento-graphql-product-no-asset-result.json
* added null checks for missing or incomplete product asset data
CIF-1631
Avoid excessive logging or null pointer exceptions when product asset data is missing.
Manually.
> CIF-1631 - NPE on PDP when product has no asset

- react-components/package-lock.json
- react-components/package.json
- react-components/src/components/Checkbox/__tests__/__snapshots__/checkbox.test.js.snap
- react-components/src/components/Checkbox/__tests__/checkbox.test.js
- react-components/src/components/Checkout/overview.js
- react-components/src/components/Minicart/productList.js
Our dependency to the Magento Peregrine library has diminished to the point that we can easily replace them with our own implementation.
CIF-1635
Unnecessary dependency
UI tests pass since the behavior was 100% reproduced.
> CIF-1635: Remove @magento/peregrine dependency

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java
- bundles/core/src/test/resources/context/jcr-content.json
- examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/page/page.html
- examples/ui.frontend/package-lock.json
- react-components/src/components/MyAccount/myAccount.js
- react-components/src/components/SignIn/useSignin.js
- react-components/src/context/ConfigContext.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/page.html
Reverts adobe/aem-core-cif-components#442
> Revert "Refresh Page on Sign-In / Refresh Page & Redirect back to Storefront on Sign-Out"

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java
- bundles/core/src/test/resources/context/jcr-content.json
- adds timewarp support in MagentoGraphqlClient
- adapts all components to be able to use the timewarp feature
- extends unit tests and re-enables some old tests and coverage
Extended unit tests and manually tested.
> CIF-1637 - Support CIF Core Components staged catalog data with Timewarp

- README.md
- VERSIONS.md
Update the versions in the documentation after release.
N/A
N/A
N/A
> @releng Update versions in the documentation after release

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/header/HeaderImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/header/Header.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/header/package-info.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/header/HeaderImplTest.java
- bundles/core/src/test/resources/context/jcr-content.json
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/header/v1/header/header.html
* expose navigationRootPageTitle in header model
* clean up Venia references in HTL
* added unit test
Clean up Venia references in Header component.
CIF-1829
JUnit, manually.
> CIF-1829 - CIF Core Header component contains hardcoded Venia strings

- README.md
- VERSIONS.md
Update the versions in the documentation after release.
N/A
N/A
N/A
> @releng: Update versions after release

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/.content.xml
Rename the CIF XF component.
CIF-1931
n/a
> CIF-1931 - rename CIF XF component

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/experiencefragment.html
Update Commerce XF placeholder message in authoring mode to display the configured placeholder.
CIF-1933
Make author life little easier.
Manually as this is just text message change.
> CIF-1933 - update XF placeholder message

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/README.md
> Updated README.md - Added "AEM as a Cloud Service" to compatibility

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
- bundles/core/src/test/resources/context/jcr-content.json
- examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java
- examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/product/manual-product/.content.xml
- it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductComponentIT.java
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/_cq_editConfig.xml
* Added dialog to product detail component to allow manual selection of a product.
* Added new page in component library to showcase the product detail component with manually selected product.
* Added DND config for product detail component, so you can drag and drop products from the sidebar on the component.
* Updated unit tests.
* Updated integration test.
* Updated component documentation.
> CIF-1908 - Allow manual product selection in product detail component

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/CategoriesRetriever.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java
- bundles/core/src/test/resources/context/jcr-content.json
- bundles/core/src/test/resources/graphql/magento-graphql-category-list-uid-result.json
- bundles/core/src/test/resources/graphql/magento-graphql-category-list-uid-sort-result.json
- bundles/core/src/test/resources/test-queries/graphql-requests.log
The order of categories and filter identifiers is now identical.
It also fixes a bug with generating the URL when UID is configured for UrlProvider
CIF-2030
The new categoryList query used in Featured Categories component does not sort the list as requested in the query filter argument
Unit test
> CIF-2030: Sort categoriesList response

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/PreviewServlet.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/PreviewServletTest.java
- add support for uid parameter
Extended unit tests and manually tested.
> CIF-2024 - CIF Add-On: UID support for "Preview with category" feature

- .circleci/config.yml
* Use new Docker images which use Azul Zulu JDK for builds and testing
* CircleCI build passes
> CIF-2014 - Migrate to Azul Zulu JDK

- README.md
Update readme, add references to CIF add-on for AEM CS & AEM 6.5
> @trivial - update readme

- .circleci/ci/it-tests.js
- .circleci/settings.xml
* CIF Add-on for SDK is available via artifactory now and the CircleCI jobs will use the latest released versions.
* If you need a snapshot version, you can update the version accordingly.
> CIF-2007 - Use latest release of CIF add-on from artifactory

- .github/release-drafter.yml
exclude "dependencies" PRs from release notes created by release notes bot
> @trivial - exclude "dependencies" PRs from release notes

- react-components/src/components/AccountContainer/accountContainer.js
- react-components/src/components/BundleProductOptions/bundleProductOptions.js
- react-components/src/components/Minicart/__test__/useMinicart.test.js
- react-components/src/components/Minicart/useMinicart.js
- react-components/src/context/UserContext.js
- react-components/src/context/__test__/UserContext.test.js
- react-components/src/utils/dataLayerUtils.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToCart.js
The dataLayer operations were moved to the appropriate context operations.
Unit tests were added to avoid regressions
CIF-2080
When the new AccountContainer component was created, the related dataLayer operations were omitted.
unit tests
> CIF-2080: Improve dataLayer operations

- README.md
add missing button component to readme
> trivial - add missing button component to readme

- react-components/package-lock.json
- react-components/package.json
- react-components/src/components/App/app.js
- react-components/src/utils/__test__/useCustomUrlEvent.test.js
- react-components/src/utils/__test__/usePageEvent.test.js
- react-components/src/utils/__test__/useReferrerEvent.test.js
- react-components/src/utils/__test__/useViewedOffsets.test.js
- react-components/src/utils/mocks/mockMagentoStorefrontEvents.js
- react-components/src/utils/useCustomUrlEvent.js
- react-components/src/utils/usePageEvent.js
- react-components/src/utils/useReferrerEvent.js
- react-components/src/utils/useViewedOffsets.js
* Adds `pageView`, `customUrl` and `referrerUrl` events to `App` component.
* Added unit tests.
* This PR was created on top of https://github.com/adobe/aem-core-cif-components/pull/579.
> CIF-2124 - Add page related storefront events

- react-components/src/components/Minicart/__test__/cartContext.test.js
- react-components/src/components/Minicart/__test__/useCartOptions.test.js
- react-components/src/components/Minicart/__test__/useMinicart.test.js
- react-components/src/components/Minicart/__test__/useProduct.test.js
- react-components/src/components/Minicart/cartContext.js
- react-components/src/components/Minicart/useCartOptions.js
- react-components/src/components/Minicart/useMinicart.js
- react-components/src/components/Minicart/useProduct.js
- react-components/src/queries/query_cart_details.graphql.js
- react-components/src/utils/__test__/__snapshots__/dataLayerUtils.test.js.snap
- react-components/src/utils/__test__/dataLayerUtils.test.js
- react-components/src/utils/dataLayerUtils.js
- react-components/src/utils/mocks/mockMagentoStorefrontEvents.js
* Added new Magento Storefront events to related cart components.
* Updated and added unit tests.
* This PR was created on top of https://github.com/adobe/aem-core-cif-components/pull/579.
> CIF-2123 - Add storefront events to Minicart

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/item.html
* fixed the markup of productlist item
CIF-2181
Manually.
> CIF-2181 - Category Pages are not correctly displayed

- extensions/product-recs/content/pom.xml
- extensions/product-recs/pom.xml
> Fix product recs extension version

- react-components/src/components/Checkout/__test__/useOverview.test.js
* Fix flaky `useOverview -> places order` test.
> CIF-2174 - Fix flaky useOverview places order test

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/SearchResultCategoryImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/SearchResultProductImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/SearchResultsStorefrontContextImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/searchresults/package-info.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/RangeBucket.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/ScalarBucket.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/SearchBucket.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/SearchFacet.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/SearchFacetType.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/SearchResultCategory.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/SearchResultProduct.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/SearchResultSuggestion.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/SearchResultsStorefrontContext.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/storefrontcontext/StatsBucket.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
- bundles/core/src/test/resources/storefront-context/result-storefront-context-search-results-component.json
- bundles/core/src/test/resources/storefront-context/result-storefront-context-search-results-sorting-component.json
- ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/storefront-events/js/collector.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/searchresults.html
The SearchResults component generates the search results context required by Magento Storefront Events SDK
CIF-2147
Required by the product recommendations engine
unit tests
> CIF-2147: Add search results to MSE

- examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/clientlibs/cif-clientlib-base/.content.xml
- examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/searchresults/.content.xml
- it/http/src/test/java/com/adobe/cq/commerce/it/http/SearchResultsComponentIT.java
* enabled productcollection v2 clientlib in examples
* updated searchresults component proxy to v2
CIF-2242
Manually.
> CIF-2242 - CIF Core Components Library product list UI is broken

- README.md
- VERSIONS.md
Update readme after release
n/a
> releng - update readme after release

- README.md
> trivial  - fix typo

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/datalayer/DataLayerComponent.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/ButtonImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/contentfragment/CommerceContentFragmentImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/experiencefragment/CommerceExperienceFragmentImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/header/HeaderImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcollection/ProductCollectionImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchbar/SearchbarImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/navigation/NavigationImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/header/HeaderImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplAssetsTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
- examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
- parent/pom.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/action.html
Removes the use of `@Inject` and replaces it with injector specific annotations. 
CIF-2210
Unit Tests, manual
> CIF-2210: replaced use of @Inject with injector specific annotations

- examples/all/pom.xml
> [DevOps] Enable continuous integration deployment to AEMaaCS

- examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/page/head.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/head.html
Add support for "brand slug" in page title. This PR replaces #611 !
CIF-2311
> CIF-2311 - add support for "brand slug" in page title

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/contentfragment/v1/contentfragment/clientlibs/editor/js/editDialog.js
Remove the leftover statement
CIF-2314
Get rid of the errors from the AEMaaCS deployment log
> CIF-2314 - CIF JS errors during AEM CS deployment step

- extensions/product-recs/react-components/src/components/ProductRecsGallery/ProductCard.js
- extensions/product-recs/react-components/src/components/ProductRecsGallery/__test__/__snapshots__/ProductCard.test.js.snap
- extensions/product-recs/react-components/src/components/ProductRecsGallery/__test__/__snapshots__/ProductRecsGallery.test.js.snap
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/categorycarousel/v1/categorycarousel/card.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/card.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/productcollection.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/item.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/image.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v1/button/button.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/header/v1/header/header.html
Added a tooltip via the `title` attribute for product image links. The following components where updated:
* Related products
* Product Carousel 
* Product Collection (v1 and v2, used by productlist and searchresults)
* Category Carousel 
* Featured Categories
* Product Teaser
* Button (v1 only)
* Header (Logo)
* Product Recommendations
> CIF-2254 - Add title attribute to product image links

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/PriceImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlToProductRetriever.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/GraphqlClientDataSourceServlet.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/GraphqlClientDataSourceServletTest.java
This PR removes the usage of APIs that are going to be removed in future cloud service releases.
CIF-2313
Unit Tests
> CIF-2313: remove use of deprecated api

- .circleci/config.yml
- it/http/src/test/java/com/adobe/cq/commerce/it/http/CatalogPagePropertiesIT.java
- it/http/src/test/java/com/adobe/cq/commerce/it/http/LandingPagePropertiesIT.java
The test with add on on https://app.circleci.com/pipelines/github/adobe/aem-core-cif-components?branch=issue%2FCIF-2299 fail because the addon bundle cannot be fully resolved.
> trivial - Update cloud image for CI

- README.md
- VERSIONS.md
Updated readme after release
n/a
> releng - updated readme after release

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/actions.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToWishlist.js
- ui.apps/test/components/commerce/product/addToWishlistTest.js
In this PR a data attribute is used to precisely identify a wish list button. It helps to improve forward compatibility in case we want to add more actions in the future.
CIF-2407, CIF-2568
Locally doing a regression test, unit tests
> CIF-2568: identify wish list button by data attribute

- examples/ui.frontend/package-lock.json
- examples/ui.frontend/package.json
- extensions/product-recs/react-components/package-lock.json
- extensions/product-recs/react-components/package.json
- react-components/package-lock.json
- react-components/package.json
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/actions.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToWishlist.js
- ui.apps/test/components/commerce/product/addToWishlistTest.js
Fixes incorrect data provided by apollo client
CIF-2567
When adding multiple variants of the same product from wishlist to cart using different options (color, size), all the products in cart display the same options as the first product added.
manually
> CIF-2567: Fix Cart product options issue

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/DeniedHttpHeaders.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/package-info.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/StoreConfigHtmlPageItem.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/package-info.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImplTest.java
- bundles/core/src/test/resources/test-queries/graphql-requests.log
> CIF-2618: make StoreConfigExporter a ConsumerType

- react-components/src/utils/__test__/hooks.test.js
- react-components/src/utils/__test__/usePageEvent.test.js
- react-components/src/utils/hooks.js
* Extended `usePageType` hook to support additional page types. The page types are used for Magento storefront events and product recommendations.
* The following page types are supported now:
* Homepage
* Content page
* Product page
* Category page
* Cart page
* Checkout page
* Updated unit tests
> CIF-2644 - Update MSE and recommendations to support more page types

- README.md
Several readme fixes:
* broken links 
* Replace Magento with Adobe Commerce
* remove some outdated parts
* remove AEM 6.4 mentions
CIF-2695 & Fixes #825
> CIF-2695 - readme fixes

- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/css/productcollection.css
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/arrow-down.svg
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/arrow-up.svg
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/chevron-down.svg
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/chevron-left.svg
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/chevron-right.svg
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/chevron-up.svg
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/resources/cross.svg
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/filters.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/pagination.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/sort.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/productlist.html
* Moved all inline SVGs from the `productcollection` markup to the clientlib resources folder. Also updated CSS accordingly.
* Added new CSS mods, so we can more easily add the beforementioned SVGs via CSS.
* `category__root--noimage` (productlist)
* `category__root--notitle` (productlist)
* `productcollection__pagination-arrow--prev`
* `productcollection__pagination-arrow--next`
* `productcollection__sort-order--asc`
* `productcollection__sort-order--desc`
If the component markup is used together with the clientlib, this is not a breaking change. However, if you rely on the svg icons being present in the markup and you don't use the component clientlib, you will need to update your customization.
* Tested the new styles with Venia and examples library
> CIF-2680 - Improve Markup of productcollection / productlist component

- README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v3/product/README.md
Making product v3 a tech preview
CIF-1696
We are planning some more, eventually breaking changes to the product component in the near future and want them to be applied on product v3.
> CIF-1696: decalare product v3 as tech preview

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/ProductSortFieldsDataSourceServlet.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcollection/ProductCollection.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcollection/package-info.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/package-info.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/searchresults/package-info.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchOptionsImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchOptions.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/Sorter.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/package-info.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/ProductSortFieldsDataSourceServletTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
- bundles/core/src/test/resources/context/jcr-content.json
- bundles/core/src/test/resources/graphql/magento-graphql-search-category-result-products.json
- bundles/core/src/test/resources/graphql/magento-graphql-search-result.json
- bundles/core/src/test/resources/graphql/magento-graphql-sortkeys-result.json
- bundles/core/src/test/resources/results/result-datalayer-searchresults-component.json
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v2/searchresults/README.md
* extended productcollection edit dialog with configuration for default sorting
* implemented support for default sorting configuration in productlist and searchresults components
* updated unit tests
CIF-2736
> CIF-2736 - Support custom sort keys in product listing components

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/package-info.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java
- bundles/core/src/test/resources/context/jcr-content.json
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/README.md
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/actions.html
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/js/actions.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/image.html
- ui.apps/test/components/commerce/productteaser/actionsTest.js
* added linkTarget option to product teaser edit dialog
* implemented link target for CTA action and teaser image link
* added unit tests
* updated readme
CIF-2730 
Manually, unit tests, UI tests.
> CIF-2730 - Product Teaser: add option to open CTA in a new Tab

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v3/page/PageImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/PageTypeRenderConditionServlet.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/navigation/Navigation.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/navigation/package-info.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v3/page/PageImplTest.java
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/catalogpage/v3/catalogpage/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/catalogpage/v3/catalogpage/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v3/page/.content.xml
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v3/page/_cq_dialog/.content.xml
This PR creates a copy of the CIF v2 page inheriting from v3 of the WCM Core Components.
CIF-2289
Support of the v3 page features, in particular async clientlib loading.
Manually, using the existing e2e tests in Venia
> CIF-2289: create a v3 cif page

- README.md
- VERSIONS.md
* updated version numbers in docs after the release
> CIF-2850 - 2022.06.0 Release Post Actions

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/AbstractPageDelegator.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/AbstractPageDelegatorTest.java
Fixed page type for datalayer.
CIF-2887
JUnit, manually.
> CIF-2887 - Wrong page component in datalayer

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/CategoryRetriever.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchAggregationOptionImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchAggregationOption.java
- bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/package-info.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
- bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
- bundles/core/src/test/resources/graphql/magento-graphql-search-category-result-category.json
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/filters.html
* enabled category filter for product list, only direct child categories are included
* updated unit tests
CIF-2686
Manually, unit tests, UI tests.
> CIF-2686 - Filter by category in product list component UI

- README.md
- VERSIONS.md
updated version numbers in docs after the release
> CIF-2902: 2022.07.0 Release Post Actions

- .devcontainer/devcontainer.json
- README.md
* Added `.devcontainer/devcontainer.json` to describe environment to launch project in GitHub Codespaces
* Added badge to README
> Add Support for GitHub Codespaces

- .circleci/config.yml
> releng: update to latest CS release 9398

- .circleci/config.yml
* Fix `jest` unit tests of `react-components` subproject.
> Fix jest unit tests

- bundles/core/pom.xml
- parent/pom.xml
> @releng - updated impsort-maven-plugin to version 1.9.0

- .circleci/config.yml
- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/storefrontcontext/SearchResultsStorefrontContextImpl.java
- bundles/core/src/test/resources/storefront-context/result-storefront-context-search-results-component.json
- bundles/core/src/test/resources/storefront-context/result-storefront-context-search-results-sorting-component.json
- extensions/experience-platform-connector/README.md
- extensions/experience-platform-connector/package-lock.json
- extensions/experience-platform-connector/package.json
- extensions/experience-platform-connector/src/events-collector/processors/processSearchResultsStorefrontData.js
- extensions/product-recs/content/package-lock.json
- extensions/product-recs/content/package.json
- upgrade to latest version of collector
- generate search results view event
- remove context from search events (should be picked up from data layer)
- return facets as list instead of null (schema validation failures)
> Aep extension fixes

- bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/sitemap/ProductsSitemapGenerator.java
> [SITES-17034] Increase the default pagination size

- README.md
- VERSIONS.md
* updated versions after release
> SITES-17835 - Release CIF Components 2.12.4

- README.md
- VERSIONS.md
> [SITES-19186] - Release CIF Components 2.12.6

- ui.apps/package-lock.json
- ui.apps/package.json
- ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/PriceFormatter.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/product.js
- ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v3/product/clientlib/js/product.js
> CIF-3024: Resolves the DOM XSS issues

- README.md
- VERSIONS.md
> @releng - updated versions after release

- bundles/core/src/main/java/com/adobe/cq/commerce/core/cacheinvalidation/internal/InvalidateCacheImpl.java
> SITES-21278: Resolve the clear cache from internal memory
