bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
Fixed NullPointerException that might occur when calling `getDescription` for a product or product variant.
```
Caused by: java.lang.NullPointerException: null
at com.adobe.cq.commerce.core.components.internal.models.v1.product.ProductImpl.getDescription(ProductImpl.java:122) [com.adobe.cq.commerce.components.core:0.0.1.SNAPSHOT]
```
=> CIF-827 - Fix NPE in product model for getDescription

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/product/v1/product/clientlib/js/product.js
Fixes a JavaScript console error that occurred for products and product variants without assets.
```
Uncaught TypeError: Cannot set property 'src' of null
at Product._onUpdateVariant (clientlib.js:450)
at VariantSelector._onSelectVariant (clientlib.js:360)
```
=> CIF-832 - Fix JS error for variants without assets

ui.apps/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml, ui.apps/src/main/content/jcr_root/conf/venia/settings/wcm/template-types/empty-page-template/policies/.content.xml, ui.apps/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml, ui.apps/src/main/content/jcr_root/conf/venia/settings/wcm/templates/search-results/policies/.content.xml, ui.content/src/main/content/jcr_root/content/venia/.content.xml
Fixes the Warnings in error.log "Ignoring reference to /conf/venia/settings from /conf/venia/settings - Probably misconfigured as it ends with '/settings'"
CIF-828
See description, fixed annoying log warning message if pages are open in AEM editor.
Manually by watching the logs and make sure the message disappears.
=> CIF-828 Warnings in error.log when page opened in page editor

ui.apps/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml
Fixed one more `Probably misconfigured as it ends with '/settings'" warning` on the product detail page.
CIF-828
See above.
=> CIF-828 fix "Probably misconfigured as it ends with '/settings'" warning

ui.content/src/main/content/jcr_root/content/venia/language-masters/en/products/.content.xml, ui.content/src/main/content/jcr_root/content/venia/us/en/.content.xml, ui.content/src/main/content/jcr_root/content/venia/us/en/products/.content.xml
Updated feedback from verification. 
* Remove obsolete `catalogRoot` property.
* Fix `jcr:language` language tag.
For reference: The refsquad is recommending to use the Page API to get the language (https://git.corp.adobe.com/CQ/wcm/blob/master/bundles/cq-wcm-api/src/main/java/com/day/cq/wcm/api/Page.java#L357).
=> CIF-722 - Remove obsolete properties

ui.apps/pom.xml
As discussed, the components are using `cifcategoryfield` and `cifproductfield` components that are in the https://github.com/adobe/commerce-cif-connector project. Therefore I added a dependency to the content package that includes the pickers to the content package that includes the components.
=> CIF-738 - Add missing dependency to authoring tooling

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
Page navigation was not directing to correct page, instead only page1 was loaded for all links.
Fetch category was being called before Page cursor's correct value was set from URL param, Appropriate logic taken out of `setupPagination()` and included in `setNavPageCursor()`  and called in right sequence, Test method also updated.
fixes issue CIF-907 
Fixes bug reported in CIF-907
Automated test cases and manual testing on Firefox, Chrome.
=> Fix for CIF-907

ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/PageContext.js
Before that fix, the `cif.cart` cookie was set on the path the user first enters the page. As long as the user enters the page via the navigation root, everything is fine. However, if a user visits the page a first time via a product page, the cart cookie is set on that page and not visible to anything above in the hierarchy. This leads to multiple cart cookies.
=> Fix path of cif.cart cookie

ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/product.js, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html, ui.apps/src/test/components/commerce/product/productTest.js
This use case is based one CIF-739. The price listed on the top right corner of the image (attached) needs to be client-side rendered. This is because price could be a personalized product attribute and showing this as client-side rendered in the reference product detail component will provide developers with an example to showcase how server-side rendered content can be enhanced with client-side content.
I added a new function in the `CommerceGraphqlApi.js` file that allows fetching of prices for one or multiple products. The same function can also be used for CIF-804.
=> CIF-743 - AEM core component - Product Detail with Price (CSR)

all/pom.xml, bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java, bundles/core/src/test/resources/graphql/magento-graphql-category-result.json, parent/pom.xml, pom.xml, ui.apps/pom.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/README.md, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/_cq_design_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/clientlibs/dist/css/productlist-aem.css, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/image.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/productlist.html
Currently, Venia uses a feature in their store front that display a category image on the category page. By implementing this feature in our AEM Venia store front, we can make our store front visually more appealing.
* Because of API changes in the sling model, I bumped the current snapshot version to 2.0.
* Added image to product list component. Will only be displayed when `showImage` property from the design dialog is true and the category has an actual image.
=> CIF-899 - Display category image on generic category page

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/gallery.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/price.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/quantity.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/variantselector.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/item.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/paginationbar.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/productlist.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/title.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/item.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/searchresults.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/heroimage/v1/heroimage/heroimage.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/footer/v1/footer/footer.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/header/v1/header/header.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/group.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/item.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/itemContent.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/navigation.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/navigationHeader.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/navigationTrigger.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/head.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/page.html
Update the copyright headers to use the correct comment formatting for HTL.
CIF-929
Copyright headers using HTML style comments are rendered in the final HTML.
N/A
=> CIF-929 - Core Components copyright headers are rendered to HTML

.circleci/codecov.yml, .circleci/config.yml, bundles/core/pom.xml
* Enable Jacoco coverage check for Java unit tests. This check is automatically performed for every Maven build. Threshold is **55%**.
* Enable Codecov coverage check for Java and Karma unit tests. Thresholds are as follows:
|                | Java | Karma |
| -------- | ----- | ------ | 
| New       | 55%  | 90%   |
| Existing | 55%  | 90%   |
* In the next weeks we will steadily increase those thresholds.
* Use CircleCI Codecov Orb instead of Codecov bash uploader.
=> Enforce code coverage for Java and Karma unit tests

parent/pom.xml
This PR fixes the maven central auto-release of a staging repository.
CIF-939
During the last release of version 0.2.0 the artifacts have not been automatically published to maven central repo. The staging repo on Nexus stayed in the open state.
Manually locally be creating a dummy release and pushing it to nexus with `<autoReleaseAfterClose>false</autoReleaseAfterClose>`so nothing was made public. That worked, the project was closed. Snippet from the release log: 
```
[INFO] Performing remote staging...
[INFO]
[INFO]  * Remote staging into staging profile ID "554a1ea838367e"
[INFO]  * Created staging repository with ID "comadobecommercecif-1050".
[INFO]  * Staging repository at https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comadobecommercecif-1050
...
Uploaded …
```
=> CIF-939 - fixes the maven central auto-release

.gitignore, README.md, ui.apps/karma.conf.js, ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js, ui.apps/test/clientlibs/common/commerceGraphqlApiTest.js
* Updated `_fetchGraphql` method to support cached GraphQL requests by using HTTP GET requests and passing the query as query parameter and un-cached requests via HTTP POST.
* Added unit tests for `CommerceGraphqlApi`.
* This will only work with Magento 2.3.2. Magento 2.3.1 does not support GraphQL requests via HTTP GET.
* Refactored `CommerceGraphqlApi` to use JavaScript modules to be easily unit testable.
* Added `@babel/polyfill` to karma, since it'a a runtime dependency after the webpack build.
=> CIF-942 - Update client-side components to use GraphQL caching

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/MagentoGraphqlClient.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/MagentoGraphqlClientTest.java
- changed default HTTP method to GET when fetching GraphQL data
To support Magento caching, the components will use GET requests.
This has been manually tested. We do not yet have any integration tests that we can use to test the components within AEM.
=> CIF-944 - Update server-side components to use GraphQL caching

ui.apps/karma.conf.js, ui.apps/pom.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/README.md, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/variantSelector.js, ui.apps/test/components/commerce/product/variantSelectorTest.js
* Product component (variant selector) now respects variant SKUs in the location hash and displays the correct variant accordingly
* Product component (variant selector) sets the SKU of the currently selected variant in the location hash
* Using the `history` API, it is possible to go back to previously selected variants using the browser's back button.
* Remove webpack info output from karma test runner
* Fix Maven phase of webpack execution
=> CIF-964 - Allow the selection of a product variant in the generic CIF product page URL

dispatcher/conf/magento-proxy.conf
Add the required configuration to the `magento-proxy` configuration file.
`mod-ssl` and SSLProxyEngine have to be configured so that the proxy allows connections via HTTPS
CIF-994
Connection via HTTPS to the Magento backend
Functional testing.
=> CIF-994 - The sample Magento proxy config doesn't support SSL

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/Utils.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/ButtonImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCateogoryListImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/header/HeaderImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListItemImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchbar/SearchbarImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserActionItem.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/teaser/CommerceTeaserImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/utils/SiteNavigation.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/MagentoGraphqlClientTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/utils/SiteNavigationTest.java
- moved `MagentoGraphqlClient` to a new (exported) package `com.adobe.cq.commerce.core.components.client`
- moved all navigation related methods from `Utils` to a new (exported) package and class `com.adobe.cq.commerce.core.components.utils.SiteNavigation`
- left the method `buildPriceFormatter` in the existing `Utils` class ... I'm not sure we also want to export it
Let me know what you think or provide alternatives if you don't like the new classes and packages names.
=> CIF-991 - MagentoGraphqlClient & Utils should be public

ui.apps/src/main/javascript/minicart/.eslintrc.js, ui.apps/src/main/javascript/minicart/src/components/Button/button.js, ui.apps/src/main/javascript/minicart/src/components/Checkout/editableForm.js, ui.apps/src/main/javascript/minicart/src/components/Checkout/flow.js, ui.apps/src/main/javascript/minicart/src/components/Checkout/form.js, ui.apps/src/main/javascript/minicart/src/components/Checkout/paymentsForm.js, ui.apps/src/main/javascript/minicart/src/components/Checkout/receipt.js, ui.apps/src/main/javascript/minicart/src/components/Checkout/shippingForm.js, ui.apps/src/main/javascript/minicart/src/components/Minicart/body.js, ui.apps/src/main/javascript/minicart/src/components/Minicart/container.js, ui.apps/src/main/javascript/minicart/src/components/Minicart/emptyMinicartBody.js, ui.apps/src/main/javascript/minicart/src/components/Minicart/footer.js, ui.apps/src/main/javascript/minicart/src/components/Minicart/minicart.js, ui.apps/src/main/javascript/minicart/src/utils/hooks.js
Clean-up the linting errors: update props validation and remove left-over `console.log` messages.
Clean-up all the linting errors by updating props and removing `console.log` messages. We allowed warning and error messages as a very crude form of error reporting.
CIF-965
`npm run lint` reports no errors or warnings.
=> CIF-965 - Implement client side cart & checkout for CIF

ui.apps/src/main/javascript/minicart/src/utils/hooks.js
The problem was caused by the poor implementation of the `useGuestCart` hook. The hook was retrying the query if it failed the first time, and it did so indefinitely.
Moving the `createCart` call outside the `useEffect` hook fixed the issue.
CIF-1044
Using the Venia storefront in author more caused the browser to become unresponsive.
=> CIF-1044 - Page becomes unresponsive in author instance on localhost

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/.content.xml
Make product detail component visible for authors as part of making the PDP fully author-able. Also see CIF archetype PR https://github.com/adobe/aem-cif-project-archetype/pull/44
CIF-1048 & https://github.com/adobe/aem-cif-project-archetype/issues/38
Product detail component in AEM editor with full authoring tooling available.
=> CIF-1048 - Make PDP template fully author-able

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/.content.xml
Make product list component visible for authors as part of making the PLP/category page fully author-able. Also see CIF archetype PR https://github.com/adobe/aem-cif-project-archetype/pull/45 which contains the bigger part of this change
CIF-1049 & https://github.com/adobe/aem-cif-project-archetype/issues/38
Product list component in AEM editor with full authoring tooling available.
=> CIF-1049 - Make PLP template fully author-able

ui.apps/src/main/javascript/minicart/src/context/UserContext.js, ui.apps/src/main/javascript/minicart/src/context/__test__/UserContext.test.js, ui.apps/src/main/javascript/minicart/src/queries/mutation_revoke_customer_token.graphql
* Call the `revokeCustomerToken` mutation when signing out.
* Fix a bug which was causing the cookie not to be removed, but set to an empty value instead.
* Update unit tests
CIF-1078
Security risk: the customer token cookie was removed but it wasn't revoked server-side, so anyone who made a copy of that cookie could issue queries using the token in the authorization header.
Functional testing, update unit tests
=> CIF-1078 - Signing out of the demo store doesn't revoke the customer token

ui.apps/src/main/javascript/minicart/src/index.js
Similar to https://github.com/adobe/aem-core-cif-components/pull/131 the React components that use the Apollo client to send GraphQL requests now respect the `cq:magentoStore` property to include a `Store` header in the requests.
1. Add a product to the cart. Verify that the client-side GraphQL requests (both for adding the product and retrieving the cart) contain a `Store: default` header.
2. Configure the website to use a different storeview, e.g. `venia`. You can do that by setting the `cq:magentoStore` property on a page. Repeat step 1 and verify that the header has changed.
=> CIF-1058 - Cart/Checkout do not respect multi store hierarchy configuration

ui.apps/src/main/javascript/minicart/src/context/UserContext.js
The `isCreatingCustomer` property of the state needs to be reset after the "Create Account" operation finishes. Ideally, this property will follow the `loading` state of the mutation, but this leads to unnecessary state updates.
CIF-1119
The "Create Account" operation cannot be performed twice in a row by an user.
Functional tests
=> CIF-1119 - Submit button on Create Account page is greyed out

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v1/button/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/_cq_dialog/.content.xml
- removed rootPath property in components with product picker
- hide rootPath property from parent component for the content teaser
Manually tested with product carousel, teaser, and button component.
=> CIF-1105 - Unneeded rootPath attribute in component edit dialogs

bundles/core/pom.xml, parent/pom.xml
See https://github.com/adobe/aem-cif-project-archetype/pull/54.
=> CIF-1108 - Update WCM core components dependency to 2.7.0

parent/pom.xml, react-components/src/components/Checkout/__test__/__snapshots__/editableForm.test.js.snap, react-components/src/components/Checkout/__test__/editableForm.test.js, react-components/src/components/Checkout/editableForm.js, react-components/src/utils/__test__/hooks.test.js, react-components/src/utils/hooks.js
* Fixes "Country US is not an available country" error in address forms during checkout.
* Manual testing
* Updated unit test
=> CIF-1120 - Make loading of countries in checkout more robust

react-components/package-lock.json, ui.apps/package-lock.json, ui.apps/package.json
* Security related update of NPM dependencies to make `npm audit` pass.
* Unit tests
=> Security related update of NPM dependencies

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeviewexporter/StoreViewExporterImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java, bundles/core/src/test/resources/context/jcr-content.json, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/catalogpage/v1/catalogpage/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/rootpage/v1/rootpage/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/rootpage/v1/rootpage/_cq_dialog/.content.xml
Fixed the MSM rollout of multi site/store content structures of the store view property. The old property (`cq:magentoStore`) was excluded by MSM rollout and was changed to `magentoStore`. The old property still can be used (for content structures not using MSM) as fall back.
The`cq:graphqlClient` property is now only editable on the site root page to not run into MSM rollout issues and not confuse authors and different properties being available at different levels.
For that, it introduces a "root" page which is the only page of the site structure that has `cq:graphqlClient` property. All child pages will only have `magentoStore`. Additionally the correct `cq:allowedTemplates` are set (in separate CIF Archetype PR https://github.com/adobe/aem-cif-project-archetype/pull/64).
A sample …
=> CIF-1149 - Fixed the MSM rollout of multi site/store content structures and make cq:graphqlClient property only editable on the site root page

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java, bundles/core/src/test/resources/context/jcr-content.json, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/actions.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/js.txt, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/clientlibs/js/actions.js, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html, ui.apps/test/components/commerce/productteaser/actionsTest.js, ui.apps/webpack.config.js
Allow authors to configure a Call-to-action button for the Product Teaser component. The Call To Action can be one of the following:
* "Add To Cart" - add the selected variation to the cart
* "See More Details" - navigate to the PDP for that product
CIF-1175
Allow visitor conversions from the teaser component
=> CIF-1175 - Call-to-action button for product teaser

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/actions.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/product.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/quantity.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/productlist.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/searchresults.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/footer/v1/footer/footer.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/navigationHeader.html
- added i18n option to all hard-coded user-facing strings
=> CIF-1148 - i18n support for AEM server-side Core Components

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductsRetriever.java
In the Magento 2.3.4 schema, the product query no longer accepts `ProductFilterInput` instances. All occurrences needed to be replaced with the new `ProductAttributeFilterInput` since otherwise the build fails. 
* Unit tests
=> CIF-1226 - Update Product Filters in Components for Magento 2.3.4 Schema

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java, bundles/core/src/test/resources/graphql/magento-graphql-productteaser-result.json, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html
* Added advanced price fetching to product teaser.
* CSS changes are done in https://github.com/adobe/aem-cif-project-archetype/pull/84.
* Manual and updated unit tests.
- X ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
=> CIF-1251 - Add advanced pricing information to product teaser

parent/pom.xml, react-components/package.json, react-components/pom.xml, ui.apps/pom.xml
- fix release, dist/ folder should not be deleted
- "moved" npm prepare script to maven clean plugin
`npm publish` calls the `prepare` script: this actually deleted the `dist` folder so it broke the webpack build and also makes the released modules unusable because the `package.json` file specifies that the module is in `dist/index.js` but this was deleted by the release job. 
Locally tested by changing the POM to do `npm publish --dry-run`
=> CIF-1229 - Release fails after npm publish

ui.apps/package-lock.json, ui.apps/package.json, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/clientlibs/js/navigation.js, ui.apps/test/components/commerce/navigation/navigationTest.js
* fixed navigation header for empty navigation
CIF-1282
Manually, unit test
=> CIF-1282 - Navigation header is broken for empty navigation

react-components/src/components/Minicart/__test__/__snapshots__/discountList.test.js.snap, react-components/src/components/Minicart/__test__/__snapshots__/product.test.js.snap, react-components/src/components/Minicart/__test__/cartOptions.test.js, react-components/src/components/Minicart/__test__/discountList.test.js, react-components/src/components/Minicart/__test__/productlist.test.js, react-components/src/components/Minicart/body.css, react-components/src/components/Minicart/body.js, react-components/src/components/Minicart/cartOptions.js, react-components/src/components/Minicart/discountList.css, react-components/src/components/Minicart/discountList.js, react-components/src/components/Minicart/footer.js, react-components/src/components/Minicart/product.css, react-components/src/components/Minicart/product.js, react-components/src/components/Minicart/totalsSummary.css, react-components/src/components/Minicart/totalsSummary.js, react-components/src/queries/query_cart_details.graphql
* Cart totals now respect discounts.
* Display line item and total prices that also respect discounts.
* Display list of applied discounts.
* Jest tests updated
=> CIF-1154 - Support discounts in shopping cart

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java, bundles/core/src/test/resources/context/jcr-content.json, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/featuredcategorylist.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcarousel.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/README.md, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/searchresults/v1/searchresults/README.md
Use generic authoring placeholder of WCM Core Components for all CIF Core Components which have custom placeholders today and used by authors.
Corresponding Archetype PR https://github.com/adobe/aem-cif-project-archetype/pull/89 to clean up the obsolete CSS.
CIF-1237
manually
=> CIF-1237 - Use generic authoring placeholder of WCM Core Components for all CIF Components

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java, bundles/core/src/test/resources/graphql/magento-graphql-category-result.json, bundles/core/src/test/resources/graphql/magento-graphql-productcarousel-result.json
* fix NPE in product list when small image is missing for a product
* fix NPE in product carousel when thumbnail is missing for a product
Product list component doesn't display a product if the product doesn't have a small_image (property is null) and it logs null pointer exception.
The same applied to the product carousel when a product doesn't have a thumbnail.
CIF-1314
Unit test, manually.
=> CIF-1314 - Product list doesn't display product without small image

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java, bundles/core/src/test/resources/context/jcr-content.json, ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/page.html, ui.apps/src/main/javascript/react-components/src/index.js
* Added option to cloud configuration to set client-side Magento GraphQL endpoint
* Renamed `StoreViewExporter` to `StoreConfigExporter` and added Magento GraphQL endpoint as exported property.
* Updated React and JavaScript code to get GraphQL endpoint from the page model.
=> CIF-1330 - GraphQL endpoint used by client-side code should be configurable

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelationTypesDataSourceServlet.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java
* replaced com.adobe.cq.commerce.common.ValueMapDecorator with org.apache.sling.api.wrappers.ValueMapDecorator
Class RelationTypesDataSourceServlet of related products uses com.adobe.cq.commerce.common.ValueMapDecorator and this makes the components bundle fail on AEMaaCS.
CIF-1322
Manually.
=> CIF-1342 - CIF core components bundle depends on commerce core bundle

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml
* use relative path for resource type
The product teaser edit dialog refers to cifproductfield with absolute path like:
sling:resourceType="/libs/commerce/gui/components/common/cifproductfield"
This breaks the cifproductfield in the edit dialog of the product teaser component on AEMaaCS.
CIF-1343
Manually.
=> CIF-1343 - Absolute path for resource type in product teaser edit dialog

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/HeroImage.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/categorylist/FeaturedCategoryList.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/product/Product.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productcarousel/ProductCarousel.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productteaser/ProductTeaser.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/searchresults/SearchResults.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/teaser/CommerceTeaser.java
Remove @ProviderType annotation if the interface is implemented / extended by custom code. 
This fixes CM code quality reported issue: 
> ../commerceinternalstageprogram/core/models/commerce/MyProductTeaser.java: The product interface com.adobe.cq.commerce.core.components.models.productteaser.ProductTeaser annotated with @ProviderType should not be implemented by custom code.
https://jira.corp.adobe.com/browse/CIF-1220
Custom component models should not implement / extend core component interfaces annotated with @ProviderType to avoid breaking changes in core interface.
- a SNAPSHOT package with the fix was created and added to in-project maven repo in the reference app at https://git.cloudmanager.adobe.com/stage-commerceinternalstage/CommerceInternalStageProgram-p10603/ (branch horea)
- …
=> CIF-1220: Fix CQBP-84 violation for Venia Reference

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v1/productlist/paginationbar.html
* Hide pagination bar for one page results
* Current page is not clickable anymore
CIF-1362
The current page can be clicked, this will just lead to reload of the current page and is useless > fix: current page should not be clickable
If there is only one result page, the pagination bar is visible > fix: hide pagination bar if only one result page
functional
=> CIF-1362: Pagination bar fixes

react-components/src/components/Minicart/__test__/couponForm.test.js, react-components/src/components/Minicart/__test__/couponItem.test.js, react-components/src/components/Minicart/__test__/product.test.js, react-components/src/components/Minicart/__test__/useCouponForm.test.js, react-components/src/components/Minicart/__test__/useCouponItem.test.js, react-components/src/components/Minicart/cartContext.js, react-components/src/components/Minicart/cartInitializer.js, react-components/src/components/Minicart/couponForm.js, react-components/src/components/Minicart/couponItem.js, react-components/src/components/Minicart/product.js, react-components/src/components/Minicart/useCouponForm.js, react-components/src/components/Minicart/useCouponItem.js, react-components/src/components/Minicart/useProduct.js
The problem was caused by the minicart refactoring that we've done some time ago - when the first product is added to the cart the "handlers" were not initialized. I removed the "cart handler" methods and use the actions directly.
The same problem affects the coupons feature - both "Add coupon" and "Remove coupon" were broken because of the same issue. The same fix has been applied to those as well.
CIF-1436
Fix the shopping cart functionality
=> CIF-1436 - Can't remove or edit items from shopping cart

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/services/ComponentsConfiguration.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/searchresults/SearchResultsImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java, examples/bundle/pom.xml, examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java
Replaced the references to `com.adobe.cq.commerce.common.ValueMapDecorator` with `org.apache.sling.api.wrappers.ValueMapDecorator`
CIF-1471
Always prefer Sling APIs over AEM ones.
Unit testing
=> CIF-1471 - Use the ValueMapDecorator from the Sling API instead of the one from the Commerce API

react-components/src/actions/navigation/actions.js, react-components/src/context/NavigationContext.js
Make sure that navigation panel title is always updated when pressing the back arrow on the panel.
The navigation panel title is not updated after visiting the forgot password or create account panels and pressing the back arrow in the top of the navigation panel.
CIF-1484
Manually.
- [] I have added tests to cover my changes and the overall coverage did not decrease.
=> CIF-1484 - Panel title not updated when returning to sign-in

bundles/core/macker-rules.xml, bundles/core/pom.xml, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java
Since we run multiple into the blocker of using com.adobe.cq.commerce.common.ValueMapDecorator we should ban the usage of AEM Commerce Classic API packages in CIF Core Components code.
* added macker-maven-plugin to deny the usage of classic commerce API
* fixed issues detected by the plugin
CIF-1470
Manually.
=> CIF-1470 - Ban usage of AEM Commerce Classic API for CIF Core Components

examples/README.md, examples/bundle/pom.xml, examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/config/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.config, examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/config/com.adobe.cq.commerce.graphql.client.impl.GraphqlClientImpl-examples.config
- fix issues for deployment on AEM as a Cloud Service
This fixes some remaining issues when deploying the components to AEMaaCS:
- a transitive dependency for `graphql-java` is no longer exported in AEMaaCS
- the GraphQL endpoint must be configured with an environment variable
Tested on AEMaaCS with SNAPSHOT dependencies for the examples library.
=> CIF-1416 - Add CIF Core Components to AEM Components Library Page

react-components/package.json
* Increase the version to `1.2.0` in `package.json`
* Add the `files` setting so that only `dist` and `i18n` folders are part of the final package
CIF-1522
The `@adobe/aem-core-cif-react-components` npm package has way too many files in it.
Functional testing, run `npm pack --dry-run` and inspect the output
=> CIF-1522 - Simplify the @adobe/aem-core-cif-react-components package

react-components/src/components/Minicart/__test__/useMinicart.test.js, react-components/src/components/Minicart/useMinicart.js, react-components/src/queries/mutation_add_to_cart.graphql
Convert the item quantity explicitly to a `float` before sending the query.
Other trivial things:
* remove an unused `debug` function from a test
* name the `Add to cart` mutation to show up nicely in Apollo DevTools
CIF-1533
Fix the incompatibility between our React component and the graphql schema.
=> CIF-1533 - [React components] The "add to cart" mutation uses a string instead of a float

.circleci/ci/it-tests.js, .circleci/config.yml
**Important**: the URL to download the CIF Add-On is set as a CircleCI variable `CIF_ADDON_URL`. This is obfuscated in the build output so nobody can have access to the add-on.
This has the main drawback that the version of the Add-On is also not visible, so we might forget to update it with each new release of the Add-On. Also because variables are also obfuscated in the CircleCI backend, it might become impossible with time to know which version we currently use.
We could hence maybe rename the variable to `CIF_ADDON_URL_2020_7_7_SNAPSHOT` so it would be straightforward from the name what version we use. If we release a new version of the Add-On, we would add for example the variable `CIF_ADDON_URL_2020_7_28` and update the build.
The drawback here is that we'd have to also update the …
=> CIF-1529 - Include CIF Add-On in IT setup for Cloud SDK

react-components/webpack.config.js
The styles used by the client-side components could not be overwritten because they were embedded in the JS bundle. This causes the styles to be added to the page using a `<style>` tag, which means that it took precedence over any styling that was added using custom CSS in other client libraries.
To address this I did two things:
- drop the `style-loader` from the Webpack configuration and use `MiniCssExtractPlugin` to extract the CSS in a separate file.
- change the name of the generated CSS classes to scope them to the component, i.e. `.header__root` from the `minicart` becomes `.cmp-Minicart__header__root`.
CIF-1547
Allow the styling of our client-side components
=> CIF-1547 - [React Components] Fix CSS reusability

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/image.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/productteaser.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/title.html
For better extensibility split product teaser template into additional sub-templates. Projects can overlay only the sub-template the need to customize instead of the entire component template.
CIF-1537
=> CIF-1537 - split product teaser template into sub-templates

ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/react-components/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/react-components/js.txt
* Remove obsolete `react-components` clientlib.
* The recommended approach is to use the React components as npm dependency in the `ui.frontend` package.
See https://github.com/adobe/aem-cif-guides-venia/pull/34.
=> trivial - Remove obsolete react-components clientlib

examples/README.md, examples/bundle/src/main/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServlet.java, examples/bundle/src/main/resources/graphql/magento-graphql-categorylist-breadcrumb.json, examples/bundle/src/main/resources/graphql/magento-graphql-products-breadcrumb.json, examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/GraphqlServletTest.java, examples/bundle/src/test/java/com/adobe/cq/commerce/core/examples/servlets/ResourceTypeImplementationPicker.java, examples/bundle/src/test/resources/context/jcr-content.json, examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/breadcrumb/.content.xml, examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/.content.xml, examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/.content.xml, examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/breadcrumb/.content.xml, examples/ui.content/src/main/content/jcr_root/content/core-components-examples/library/commerce/productlist/.content.xml, it/http/src/test/java/com/adobe/cq/commerce/it/http/BreadcrumbComponentIT.java, it/http/src/test/java/com/adobe/cq/commerce/it/http/NavigationComponentIT.java, it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductComponentIT.java, it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductListComponentIT.java
Adds a page for the Breadcrumb component in the components library. We also add an example of the breadcrumb on the product and productlist pages, because this is where it's most interesting. Note that these two examples are added in separate "demo" boxes because the demo component does not support rendering multiple components.
Extended integration tests.
This shows the extra example on the product page:
=> CIF-1597 - Add Commerce Breadcrumb to CIF Components Library

react-components/src/utils/hooks.js
* Whenever the React components were served from a host that includes a port, the cookies (for cart, login) could not be set, because the cookie string was invalid and was rejected by the browser.
* The variable `window.location.host` which was used to set the cookie domain includes the port if used. This is invalid according to the cookie spec.
* The variable `window.location.hostname` does not include the port and therefore provides a valid domain for the cookie.
* Manually tested using dispatcher. You can for example use `docker run -d -p 8080:80 aem-dispatcher:latest` to start the dispatcher on port `8080` to reproduce the problem.
=> CIF-1610 - Cookies are not correctly set when hostname has a port

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java, examples/bundle/pom.xml, parent/pom.xml, ui.apps/pom.xml
This PR replaces the use of `StringSubstitutor.replace()` in `UrlProviderImpl` with `StringUtils` methods to avoid adding dependency on Apache's `commons-text` package.
The `commons-text` bundle was embedded in `ui.apps` package. Embedding 3rd party bundles in application type package is now prohibitted for AEM as a Cloud Service.
- unit tests
=> CIF-1624: Remove commons-text dependency in UrlProviderImpl

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java
This is a workaround to ensure that Magento does not return a cached response for staged data.
Manually tested.
=> CIF-1644 - GraphQL requests for staged data should use POST

react-components/i18n/en/account.json, react-components/package-lock.json, react-components/src/components/ForgotPassword/forgotPasswordForm.js, react-components/src/components/ResetPassword/ResetPassword.css, react-components/src/components/ResetPassword/ResetPassword.js, react-components/src/components/ResetPassword/__test__/ResetPassword.test.js, react-components/src/components/ResetPassword/__test__/__snapshots__/ResetPassword.test.js.snap, react-components/src/components/ResetPassword/index.js, react-components/src/components/ResetPassword/useResetPassword.js, react-components/src/index.js, react-components/src/queries/mutation_reset_password.graphql, react-components/src/utils/__test__/hooks.test.js, react-components/src/utils/hooks.js, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/resetpassword/v1/resetpassword/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/resetpassword/v1/resetpassword/resetpassword.html
This PR depends on #400.
* Add new `ResetPassword` React component to display the reset password form.
* Add new `resetpassword` component to display the placeholder for the React component.
* Added unit tests.
* This feature requires setup on the Magento side, please see https://github.com/adobe/aem-core-cif-components/wiki/Configure-Reset-Password.
Please also see https://github.com/adobe/aem-cif-guides-venia/pull/60.
* Manually tested password reset workflow.
* Unit tests.
=> CIF-1084 - Implement the password reset page

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/SpecificPageFilterFactory.java
- configure filter ranking to lowest possible value, to avoid skipping the DispatcherCacheHeaderFilter filters from ACS-Commons
When it matches, the `SpecificPageFilterFactory` forwards the request to another page, and this "breaks" the chain of filters. We hence set the ranking to the lowest possible value, in particular to avoid skipping the TTL-based filters.
Manually tested with dispatcher and ACS-Commons filters.
=> CIF-1653 - TTL-based caching is skipped by the SpecificPageFilterFactory

ui.apps/pom.xml
- only enabled the validation of scripts, not the generation and compilation of scripts in java (IMHO it doesn't bring much).
=> CIF-1680 - Add htl-maven-plugin to CIF ui.apps

bundles/core/pom.xml
This should hopefully fix a build error with `CloudManager` when the maven build adds the `org.jacoco:jacoco-maven-plugin:prepare-agent` argument on the command line.
=> CIF-1777 - Jacoco build issue with CIF components library and CloudManager

.circleci/config.yml, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java
- fix unit test issues with java 8
- enable new CircleCI job to build with java 8
=> CIF-1779 - CIF components build fails with java 8

examples/ui.frontend/package-lock.json, examples/ui.frontend/package.json, examples/ui.frontend/pom.xml
- remove "prod" frontend build as "fedDev" build is now active by default
- build "prod" version of the react components, to avoid that some dependencies are included twice
- enable "quiet" option for storybook build to avoid filling the build with debug messages
- add missing "npm install" (after removing the frontend build from the "prod" profile)
The problem was that the build mixed the `webpack:dev` build of the react components with the `webpack:prod` build of the `ui.frontend` project, and the consequence was that graphql library was included twice in the final clientlib. Setting everything to `prod` by default fixes the problem.
I also fixed two other issues:
- the build was executed twice since the `fedDev` profile is also active by default
- I disabled the very long debug of the …
=> CIF-1776 - CIF components library clientlib is broken

.circleci/ci/it-tests.js, .circleci/config.yml
This optimizes the CircleCI build and avoids rebuilding all maven modules when executing the integration tests. To generate the jacoco coverage for ITs, I simply also "store" the `target` folders for the two bundles so the classes are available when generating the jacoco report and there is no need to recompile anything.
Note that this reduces the build time by 3 to 5 minutes.
=> CIF-1815 - Remove redundant builds done in CircleCI integration tests jobs

react-components/src/utils/__test__/compressQueryFetch.test.js, react-components/src/utils/compressQueryFetch.js
The GraphQL query compression that is used for GET requests fails for when the storefront is configured to use the `/api/graphql` endpoint.
This affects queries of the shopping cart and others.
* Manually tested with latest Venia snapshot
* Updated unit test
=> CIF-1918 - Query minification fails for /api/graphql endpoint

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java
This PR provides a workaround to fix an issue with Sling model caching with the datalayer. The fix is basically to "re-read" the `resource` when the datalayer data is generated to make sure that it uses the `productlist` component resource and not the page resource initially used when the component is instantiated in `PageMetadataImpl.java`.
The other part of the fix is to re-create the list of products to make sure that the resource types and paths are correct when generating the datalayer data.
These two fixes are a temporary workaround to fix the bug until the implementation is refactored to fix the issue in a nicer way.
See https://github.com/adobe/aem-cif-guides-venia/pull/104 and also manually tested.
=> CIF-1955 - Venia ITs fail for productlist

bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/datalayer/AssetDataImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/ProductList.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/package-info.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java, bundles/core/src/test/resources/context/jcr-content-breadcrumb.json, examples/ui.apps/src/main/content/jcr_root/apps/cif-components-examples/components/page/head.html, it/http/src/test/java/com/adobe/cq/commerce/it/http/CommerceTestBase.java, it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductComponentIT.java, it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductListComponentIT.java, it/http/src/test/resources/datalayer/chaz-kangeroo-hoodie-product.json, it/http/src/test/resources/datalayer/outdoor-productlist-items.json, it/http/src/test/resources/datalayer/outdoor-productlist.json
This PR solves a bug related to Sling model caching: it now ensures that the right `product` or `productlist` resource is used when adapting to the `Product` or `ProductList` component. The change is pretty small, most of the changes relate to unit and integration tests.
Enabled Sling model caching in unit tests (by using the right maven dependency), and also enabled the use of the `PageMetadata` component on the pages of the CIF components library, so we can test Sling model caching and also the datalayer data to make sure this works as expected.
=> CIF-1962 - Sling model caching introduces issues with PageMetadataImpl

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/XFDialogExtensionsRenderConditionServlet.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/XFDialogExtensionsRenderConditionServletTest.java, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/xfpage/v1/xfpage/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/xfpage/v1/xfpage/_cq_dialog/.content.xml
- create xfpage cif component with XF dialog extensions
- create rendercondition servlet to only display the dialog extension with the CIF Add-On bundle
This PR moves the entire `xfpage` dialog from the AEM Archetype + Venia to the CIF components in a new `xfpage` component extending `cq/experience-fragments/components/xfpage`. This way we can easily modify and push updates to customers.
In addition, we only want to display some dialog extensions when the CIF Add-On is present, so I added a new `rendercondition` that detects if the CIF Add-On bundle is available.
The corresponding Venia PR to remove the old dialogs is https://github.com/adobe/aem-cif-guides-venia/pull/114
Note that the dialog overlay added in this PR corresponds to what was until now added in the AEM archetype and needs …
=> CIF-1920 - Move XFPage dialog extensions to CIF core components

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductCarouselImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java, bundles/core/src/test/resources/exporter/productcarousel.json, bundles/core/src/test/resources/exporter/related-products.json, bundles/core/src/test/resources/exporter/upsell-products.json
- adding json exporter similar to productcarousel
Added unit tests.
=> CIF-1786 - Implement ComponentExporter for related products component

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java
Fix NPE from cases of category list containing h empty (null) objects. This should only happen in exceptional case.
CIF-2075
=> CIF-2075 - fix NPE from category list with empty objects

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/ComponentsConfigurationAdapterFactory.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/utils/SiteNavigation.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/ComponentsConfigurationAdapterFactoryTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/utils/SiteNavigationTest.java, bundles/core/src/test/resources/context/jcr-content-breadcrumb.json
Launches do not support context aware configurations in all supported product version right now. Because of that a fallback logic has been introduced to fallback to the production content of a Launch when accessing context aware configurations. This logic fails when the content was newly created in the Launch and so production content does not (yet) exists, causing NPEs in various places.
CIF-2060
CIF-2061
- Create a Launch from an existing site (e.g. Venia sample storefront)
- In the Launch, create a new content page as child of a homepage
- Open the content page for editing => fails with a NPE
- Open the Homepage => navigation not rendered correctly, NPE
=> CIF-2060 - fix NPEs related to special handling for Launches

.circleci/config.yml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/experiencefragment/v1/experiencefragment/.content.xml
Changed title of commerce experience fragment component to "Commerce Experience Fragment".
CIF-2135
Title was too long.
Manualy.
=> CIF-2135 - Rename component to "Commerce Experience Fragment"

react-components/src/components/Checkout/__test__/editableForm.test.js, react-components/src/components/Checkout/__test__/useCart.test.js, react-components/src/components/Checkout/__test__/useOverview.test.js, react-components/src/components/Checkout/overview.js, react-components/src/components/Checkout/useCart.js, react-components/src/components/Checkout/useOverview.js, react-components/src/context/UserContext.js, react-components/src/queries/query_cart_details.graphql.js, react-components/src/utils/hooks.js, react-components/src/utils/mocks/mockMagentoStorefrontEvents.js, react-components/src/utils/mocks/mutationPlaceOrder.js, react-components/src/utils/test-utils.js, ui.apps/package-lock.json
- Added new Magento Storefront events to related checkout components.
- Updated and added unit tests.
CIF-2119
Required by the product recommendations engine
Unit tests
=> CIF-2119: Add storefront events to checkout components

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/DeniedHttpHeaders.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClient.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/package-info.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/StoreConfigExporter.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/storeconfigexporter/package-info.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/client/MagentoGraphqlClientTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/storeconfigexporter/StoreConfigExporterTest.java, react-components/src/components/App/app.js, react-components/src/context/ConfigContext.js, ui.apps/package-lock.json, ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/page.html, ui.apps/test/clientlibs/common/commerceGraphqlApiTest.js
Users may configure additional HTTP headers to be sent with each Graphql request, via the `CIF HTTP Custom Headers configuration` service and the cloud service configuration. This PR updates the `MagentoGraphqlClient` to consume custom HTTP headers from the CA config.
CIF-2097 
Allow the components to consume the custom HTTP headers.
Unit testing, functional testing
=> CIF-2097 - Consume the configured custom HTTP headers in MagentoGraphqlClient

bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImplTest.java
With the UID changes the "Category Filter" (using category_id) became available on category pages as it could not be matched against the current category page identifier anymore (since it is a uid now).
Selecting the "Category Filter" does not make sense and leads to GraphQl errors because of combined `category_id` and `category_uid` filters.
This PR removes the `category_id` based aggregation for category pages. Full text search behavior has not changed.
CIF-2206
Extended unit tests.
=> CIF-2206 - Fix category_id filters being present on category pages

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java
Regression: do not enable Sling model caching for MagentoGraphqlClientImpl because the `RequestOptions` for the GraphQlClient (which also influence caching behaviour) are cached with Sling Model caching.
CIF-2209
=> CIF-2209 - do not enable Sling model caching for MagentoGraphqlClientImpl

bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/AggregationOptionToSearchAggregationOptionConverter.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/AggregationToSearchAggregationConverter.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
Since we removed id support and with #602 we can further improve the urls on product list pages by removing the redundant category_uid url parameter.
CIF-2208
User friendly urls
Unit Tests, Manual using Venia
=> CIF-2208: remove category_uid request parameter on product lists

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/ProductListItem.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/common/package-info.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/converters/ProductToProductListItemConverter.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/common/ProductListItemTest.java
`ProductListItem` did not give any access to the full product retrieved from backend, hence extended queries with custom attributes did not work since the retrieved custom attributes could not be accessed.
With this the a project developer gets access to the entire product retrieved from the backend.
CIF-2305
Added unit test.
=> CIF-2305 - fix raw product access for mapped product product list items

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/card.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/carousel.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/carousel/v1/carousel/clientlibs/css/carousel.css, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/categorycarousel/v1/categorycarousel/card.html, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/clientlibs/css/productcarousel.css, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/productcard.html, ui.apps/test/components/commerce/carousel/carouselTest.js
* Removed invalid aria roles.
* Changed button positioning (in DOM only), so that both buttons are in tab order before the cards.
* Added `title` and `aria-label` to buttons.
* Updated CSS to includes styles to differentiate between disabled and focused (via keyboard only) states of the buttons.
* Updated markup in unit test.
* Manually tested by using the components via keyboard only.
=> CIF-2279 - Improve accessibility of carousel components

bundles/core/src/main/resources/productlist-component-placeholder-data.json
This PR removes the sku's from the productlist's placeholder data. This makes sure that they are not rendered to the markup as data attributes and so are not picked up by the associated content tab.
CIF-2334
Unit Tests, Locally
=> CIF-2334: remove skus from placeholder data

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java, bundles/core/src/test/resources/context/jcr-content-breadcrumb.json
Fix the null pointer exception in PageMetadataImpl when the target component is not found on a product page or product list page.
CIF-2268
JUnit, manually.
=> CIF-2268 - Removing product list component from category template breaks the page

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbImplTest.java
Fixed NPEs when dynamic categoryPage or productPage is null.
CIF-2215
=> CIF-2215 - Breadcrumb error when no dynamic category page is present

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java
Ensure that the resource type of the component proxy is used for cache name.
For instance currently the cache name for navigation component is: core/cif/components/structure/navigation/v1/navigation
while it's supposed to be: venia/components/commerce/navigation
CIF-2298
Fixes #646.
This was the initial behavior but internal modification changed it.
=> CIF-2298 - Menu cache flush is not working as expected

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProviderTest.java, bundles/core/src/test/resources/graphql/magento-graphql-navigation-result.json
* don't include categories where the property include_in_menu is 0
* minor refactoring for easier testing
* updated unit tests extending them to also cover category ordering and exclusion of unnamed categories
CIF-2312
=> CIF-2312 - Respect "include_in_menu" property in navigation component

examples/all/pom.xml, examples/bundle/src/main/resources/graphql/magento-graphql-productteaser.json
The alt text for the product teaser component depends on the image label. This label was not included in the mock response used for the examples project.
Additionally, I added a missing WCM examples config package to the `include-wcm-components-examples` profile which blocked the installation when building the all package with that profile.
Closes #683.
Manually tested by installing the examples project.
=> CIF-2367 [Accessibility][Product Teaser] The product image has an insufficient alternative text attribute

react-components/src/utils/__test__/createProductPageUrl.test.js, react-components/src/utils/createProductPageUrl.js
With #654 a caching mechanism was introduced to `createProductPageUrl()` in order to prevent querying for the store config meta element multiple times. This causes a regression as the caching stored a full product url and returned it in subsequent calls instead of just the storeRootUrl part. This PR removes the caching and adds more coverage to the method to validate the behaviour for subsequent calls.
#654 CIF-2292
CIF-2578
Regression introduced in CIF-2292
Unit tests and locally
=> CIF-2578: fix createProductPageUrl caching

.github/workflows/maven-deploy-to-library.yml
Change to nightly schedule for CIF Core Components library deployments for aemcomponents.dev, but only if we have changes on the default branch.
For commit check in last 24h see https://stackoverflow.com/questions/63014786/how-to-schedule-a-github-actions-nightly-build-but-run-it-only-when-there-where
CIF-2614
Reduce the deploy frequency. At the moment we deploy on every PR merge to master. This is too ofter since it will also trigger for unimportant PRs like renovate dependency fixes.
=> CIF-2614 - change to nightly schedule

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/account/MiniAccountImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productteaser/ProductTeaserImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/account/MiniAccountImplTest.java, extensions/product-recs/bundle/pom.xml, extensions/product-recs/bundle/src/main/java/com/adobe/cq/commerce/extensions/recommendations/internal/models/v1/productrecommendations/ProductRecommendationsImpl.java, extensions/product-recs/bundle/src/test/java/com/adobe/cq/commerce/extensions/recommendations/internal/models/v1/productrecommendations/ProductRecommendationsImplTest.java
Wish lists can be enabled/disabled per store configuration. this information is available as part of the store config query. However as the configuration does not change often, it does not make much sense to query it for each page rendering that requires this information. Because of that we added a (feature) configuration to the CIF context aware configuration which can be automatically set from the store configuration with the next release of the CIF addon. 
CIF-2580
CIF-2407
Unit Tests, manual verifcation
=> CIF-2580: disable wish lists from store configuration

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/clientlib/js/addToWishlist.js, ui.apps/test/components/commerce/product/addToWishlistTest.js
When adding a grouped product to wishlist, use the sku of the grouped product, not individual items
CIF-2602
When adding group products to the wish list they get randomly added multiple times (in tests twice). Compared to venia.magento.com we add each product with a parent_sku, pwa studio only adds the grouped product itself.
unit test
=> CIF-2602: Grouped products added multiple times to Wish List

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/xfpage/v1/xfpage/_cq_dialog/.content.xml, ui.apps/test/components/content/teaser/teaserConfigTest.js
* The `filter` attribute was deprecated some time ago when we started to derive it from the `selectionId`. Since its value is not respected anymore, we can simply remove it. This applies to usage of the CIF Core Components together with the CIF add-on only.
=> CIF-2650 - Remove unused filter attribute of product picker

ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v2/page/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/xfpage/v1/xfpage/_cq_dialog/.content.xml
This PR enables the preview date filter for product pickers in the Page properties.
Inside a Launch and when using Timewrap, the product pickers are already preconfigured for staged catalog data. For places that are not accessible in this context, the same should be possible using a filter inside the picker itself.
CIF-2560
=> CIF-2560: enable preview filter for product pickers

.circleci/config.yml
* Replaced Azul JDK images with new ones using OpenJDK.
* Adapted to new pattern to install browsers for UI testing via `circleci/browser-tools` orb, since they are no longer included in the images.
Via CircleCI
=> releng - Replace Azul JDK with OpenJDK images

ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v2/page/_cq_dialog/.content.xml
* fix the commerce tab contents in category page properties
CIF-2766
Manually, UI test (in Venia)
=> CIF-2766 - Commerce property tab for category template page is broken

it/http/src/test/java/com/adobe/cq/commerce/it/http/CatalogPagePropertiesIT.java, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v2/page/_cq_dialog/.content.xml
When having a site that features multiple "shop" entries with different product/category pages it must be possible for editors to define the references to those. From an implementation perspective this is already possible as the `cq:cifProductPage` and `cq:cifCategoryPage` properties are inherited down the hierarchy. However it is not possible to set them anywhere else than on the landing page.
This PR enables these properties to be set on the catalog pages.
CIF-2474
Commerce quick site creation
Locally, existing ITs adapted accordingly
=> CIF-2474: enable the Commerce Pages on catalog pages

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/product/ProductImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productlist/ProductListImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/product/ProductImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v2/productlist/ProductListImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/page/PageMetadataImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
The change removes model caching and replaces it with a request scoped cache maintained by the `MagentoGraphqlClient` model. It allows components of the same type to be used more than once on a page (in particular product list) while preserving the optimisation done to not query the commerce backend multiple times for the same component.
Existing tests cover this behaviour already.
CIF-2761
Support multiple Product List components on a single page.
Unit tests, locally manually
=> CIF-2761: replace model caching 

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/services/UrlProviderImplTest.java, bundles/core/src/test/resources/graphql/magento-graphql-product-result-url-parameters.json
This change address a regression introduced with #776 after which the sku is not always available to product url formats. 
#776 
#875 
CIF-2792
Unit Tests
=> CIF-2792: Always add SKU to product url format params

examples/ui.frontend/pom.xml, extensions/product-recs/content/pom.xml, extensions/product-recs/react-components/pom.xml, parent/pom.xml, react-components/pom.xml, ui.apps/pom.xml
With this change we move parts of frontend-maven-plugin configuration to the parent module to reduce duplication. We also update the version to the latest release.
CIF-2811
https://github.com/eirslett/frontend-maven-plugin/pull/970
Support builds on Apple Silicon with node versions older than 16
Build locally, CI
=> CIF-2811: update frontend-maven-plugin

ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v2/page/_cq_dialog/.content.xml
* Add tracking annotations to product and category filters for specific product and category pages
* E2E tests added via https://github.com/adobe/aem-cif-guides-venia/pull/275
=> CIF-2757 - Add tracking annotations for product and category filters in page properties

.circleci/config.yml
* Nightly jobs started to fail because `cimg/node:lts-browsers` CircleCI Docker images don't need permission fixes for npm anymore.
* The OpenJDK images still need it though.
=> releng - Fix jest jobs on CircleCI

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/NavigationImplTest.java
Fix navigation rendering with multiple catalog pages.
CIF-2866
Manually, JUnit.
=> CIF-2866 - Alternative category page takes over the whole navigation

extensions/product-recs/content/src/main/content/jcr_root/apps/core/cif/extensions/product-recs/components/productrecommendations/v1/productrecommendations/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/categorycarousel/v1/categorycarousel/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/featuredcategorylist/v1/featuredcategorylist/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/product/v1/product/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productlist/v2/productlist/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/relatedproducts/v1/relatedproducts/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v1/button/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v2/button/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v1/teaser/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v2/teaser/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/catalogpage/v1/catalogpage/_cq_dialog/.content.xml
* Enabled the `showLink` option for all product and category fields. This will now display a reference button (single selection) or a reference table (multi selection) with links to the selected products and categories.
* Manually tested that buttons/tables are displayed for all the updated components.
=> CIF-2127 - Enable showLink options for all product and categoryfields

ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/teaser/v3/teaser/clientlib/editor/js/teaser.js, ui.apps/test/components/content/teaser/teaserConfigTest.js
Fixing the enabling / disabling of the action fields depending on the actions checkbox status.
CIF-2884
Manually, UI tests.
=> CIF-2884 - Commerce teaser dialog clientlib regressions

.circleci/config.yml
* With npm 7+ and the new package-lock.json format, peer dependency checks got stricter and are enforced.
* Unfortunately there is an issue with peregrine 11 which requires react 17 and apollo 3.1.x, while apollo 3.1.5 (latest) only works with react 16.
* Since these peer dependencies cannot easily be fixed, we can force npm to fallback to the old peer dependency behaviour to fix the failing CircleCI build.
=> releng - Fallback to legacy peer dependency check

bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/testing/GraphqlQueryMatcher.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/testing/Utils.java
With catalogs that have a lot of custom product attributes the customAttributeMetadata query executed by the `SearchFilterServiceImpl` for Product Lists and Search Results may exceed the query parameter limit of http GET requests. Using POSTs for the GraphqlClient in question will resolve the issue but is not recommended as it by-passes any CDN caching that may be involved. 
With this change we allow the CIF Search Filter Service to be configured to enforce POST only for the customAttributeMetadata query. The option is per default disabled. If enabled we recommend to cache the response by configuring the GraphqlClient caching accordingly. 
CIF-2919
Unit tests
=> CIF-2919: allow to enforce POST requests for customAttributeMetadata query

ui.apps/src/main/content/jcr_root/apps/core/cif/clientlibs/common/js/CommerceGraphqlApi.js, ui.apps/test/clientlibs/common/commerceGraphqlApiTest.js
* Client-side GraphQL requests made via `CommerceGraphqlApi` (like client-side price fetching) now send the user token as `Authorization` header.
* This works with both the old `cif.userToken` cookie as well as the token set by Peregrine in local storage.
* Added unit tests for both cases.
* Fixes #914
* Updated unit tests.
=> CIF-2903 - Add login token to client-side price fetching

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductsRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductsRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/package-info.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/productcarousel/ProductsRetrieverTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/models/v1/relatedproducts/RelatedProductsImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetrieverTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetrieverTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetrieverTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductsRetrieverTest.java, parent/pom.xml
* Added `extendCategoryFilterWith` and `extendProductFilterWith` to retrievers that support hooks to enable full replacement or extension of category and product query filters.
* Added unit tests.
Requires a release of https://github.com/adobe/commerce-cif-magento-graphql/pull/29 before it can be merged.
See https://github.com/adobe/commerce-cif-magento-graphql/pull/27
* Unit tests + Venia example
=> CIF-2895 - Extend product retriever with hook for product filters

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/ShowNavRootRenderConditionServlet.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/servlets/ShowNavRootRenderConditionServletTest.java, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v1/page/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v2/page/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/page/v3/page/_cq_dialog/.content.xml
* Added `Landing Page` checkbox to properties page of CIF page component (v1, v2 and v3).
* Added `ShowNavRootRenderConditionServlet` to show checkbox only on pages that are either the landing page or don't have a landing page in the hierarchy.
* Added unit tests.
* UI tests in Venia
=> CIF-2673 - Add navRoot checkbox to page properties

.circleci/config.yml
* Required for being able to write in the global npm folder, which is required for running `npm link`
* via CircleCI
=> releng - Fix permissions in jest-extension job

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v1/productcollection/clientlibs/js/productcollection.js, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/js/productcollection.js
This change replaces the use of DOMParser in the load more handlers of product collections with a [`document.createRange().createContextualFragment`](https://developer.mozilla.org/en-US/docs/Web/API/Range/createContextualFragment). 
The DOMParser previously parsed the returned html without any browsing context, hence flagged as scripting disabled. This causes all nodes in `<noscript>` tags to be parsed as dom nodes. 
The image v2 component on the other hand expects the content of the `<noscript>` tag to be pure text, which is the expected for javascript enabled browsers. Because of this the image v2 component was not working for product list experience fragments in combination with load more yet.
CIF-2948
Locally, existing uint tests
=> CIF-2948: parse response html in the current browsing context

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java
Log WARN when getting duplicate id from Magento GraphQL API
Log WARN when getting duplicate id from Magento GraphQL API
https://jira.corp.adobe.com/browse/SITES-17412
There exists a way to get duplicate data from Magento GraphQL API, this possibility occurs when customers add data to their system and the indexers do not complete before data is retrieved from the system.
Do It Best was affected by this and the AEM Support Org spent weeks debugging (because it was also a very intermittent issue). Eventually, T3 deployed a custom build of the Category Feature List showcasing the GraphQL query and we discovered that the categoryIds were unique. After engaging and reviewing our findings with SITES engineering we agreed to log a ticket with Magneto Engineering which then Magento ack'd that this …
=> SITES-17412: Log WARN when getting duplicate id from Magento GraphQL API

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/CatalogPageNotFoundFilter.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/CategoryPageRedirectServlet.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/servlets/ProductPageRedirectServlet.java
Some of the servlets and filters are not yet registered for the Page v3 resource type. The functionality provided by them is missing.
#987
=> fix: add Page v3 resource type to CatalogPageNotFoundFilter and redirect servlets

extensions/experience-platform-connector/README.md
Update Experience Platform Connector README.md `Known Limitations`
- add minimum required dependencies for `EventCollectorContextProvider` to be working.
=> update README.md experience platform connector Known Limitations

ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/js/actions.js, ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcollection/v2/productcollection/clientlibs/js/productcollection.js, ui.apps/test/components/commerce/productcollection/productCollectionV2Test.js
* install addToCart and addToWishList action for items loaded with the load more button
SITES-18761
Manually.
=> SITES-18761 - productcollection - addToWishlist and addToCart buttons not working

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/breadcrumb/BreadcrumbRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/productlist/package-info.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoriesRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractCategoryRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractProductsRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractRetriever.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/models/retriever/package-info.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/models/SearchResultsSetImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/SearchResultsSet.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/search/models/package-info.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/components/models/retriever/AbstractRetrieverTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/models/SearchResultsSetImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchFilterServiceImplTest.java, bundles/core/src/test/java/com/adobe/cq/commerce/core/search/internal/services/SearchResultsServiceImplTest.java
* added getErrors() in AbstractRetriever
* provided implementation for getErrors() in existing retrievers
=> SITES-22111 - Extend core CIF graphQL resolver with new function/API to expose Errors

.circleci/config.yml, bundles/core/pom.xml, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/categorylist/FeaturedCategoryListImpl.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/CommerceLinksTransformerFactory.java, examples/bundle/pom.xml, it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductComponentIT.java, it/http/src/test/java/com/adobe/cq/commerce/it/http/ProductListComponentIT.java, parent/pom.xml, renovate.json
=> Category URL fix - convert catergoryUid back into the actual characters

bundles/core/src/main/java/com/adobe/cq/commerce/core/components/client/DeniedHttpHeaders.java, bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/services/ComponentsConfigurationAdapterFactory.java
* removed usages of com.google.common.collect (Guava)
=> SITES-29602 - core-cif-components-core: remove usage of Guava
